config/routes.rb
DotaAssistant::Application.routes.draw do
  root to: "picks#hero_picker"
  get 'pick_assistant' => 'picks#hero_picker'
  post 'pick_assistant' => 'picks#recommendation'
  post 'remaining_builds' => 'picks#remaining_builds'
  post 'remaining_heroes' => 'picks#remaining_heroes'
end

app/models/build.rb
class Build < ActiveRecord::Base
  VALID_ROLES = [
    :carry,
    :disabler,
    :durable,
    :ganker,
    :initiator,
    :jungler,
    :lane_support,
    :nuker,
    :pusher,
    :support
  ]

  belongs_to :hero

  serialize :role_elements, Array

  validates :name,
            :carry,
            :disabler,
            :durable,
            :ganker,
            :initiator,
            :jungler,
            :lane_support,
            :nuker,
            :pusher,
            :support,
            :hero_id,
            presence: true

  after_create :save_role_elements

  def balanced_role_elements
    Vector.elements(role_elements[0..1] + role_elements[3..7] + role_elements[9..role_elements.length])
  end

  def jungling_role_elements
    Vector.elements(role_elements)
  end

  def trilane_role_elements
    Vector.elements(role_elements[0..7] + role_elements[9..role_elements.length])
  end

  def hero_name
    hero.name
  end

  private

  def save_role_elements
    self.role_elements = [
      hero.attack_type == 'ranged' ? 1 : 0,
      hero.viable_mid,
      hero.viable_offlane,
      carry,
      disabler,
      durable,
      ganker,
      initiator,
      jungler,
      lane_support,
      nuker,
      pusher,
      support
    ]
    save
  end
end

app/models/hero.rb
class Hero < ActiveRecord::Base

  has_many :builds

  validates :name, :viable_mid, :viable_offlane, :attack_type, :main_attribute, presence: true

  default_scope -> { order('heroes.id ASC') }

  scope :with_role, -> (name = nil) { joins(:roles).where(roles: {name: name}).uniq }
  scope :with_main_attribute, -> (attribute = nil) { where(main_attribute: attribute) }
  scope :with_attack_type, -> (attack_type = nil) { where(attack_type: attack_type) }

  scope :radiant, -> { where(team: :radiant) }
  scope :dire, -> { where(team: :dire) }

end

app/models/heroes_role.rb
class HeroesRole < ActiveRecord::Base
  belongs_to :hero
  belongs_to :role
end

app/models/role.rb
class Role < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  COMPOSITION = {
    'ideal_balanced_vector' => '2-1-2',
    'ideal_jungling_vector' => 'Jungling',
    'ideal_trilane_vector' => 'Trilane'
  }

  respond_to :html, :js

  def hero_picker
    @heroes = Hero.all
  end

  def recommendation
    @friendlies = Build.where(id: params[:friendlies])
    @enemies = Hero.where(id: params[:enemies])
    @bans = Hero.where(id: params[:bans])

    @recommendation, @worst = Recommendations.pick_recommendations @friendlies, @enemies, @bans, params[:composition].upcase if @friendlies.count > 0

    if @enemies.count > 1
      default_build_ids = @enemies.map { |enemy| enemy.builds.first.id }
      default_builds = Build.where(id: default_build_ids, hero_id: params[:enemies])
      recommended_banned_builds = (Recommendations.pick_recommendations default_builds, @friendlies, @bans, 'BALANCED').first
      @ban_recommendations = recommended_banned_builds.map { |build| build.hero }
    end

    @composition = COMPOSITION[params[:composition]]

    @needed_roles = Recommendations.roles_needed @friendlies, params[:composition].upcase unless @friendlies.empty?
    @filled_roles = Recommendations.roles_filled @friendlies, params[:composition].upcase unless @friendlies.empty?

    respond_to do |format|
      format.json
    end
  end

  def remaining_builds
    params[:friendlies] ||= []
    params[:enemies] ||= []
    params[:bans] ||= []

    friendly_hero_ids = Build.where(id: params[:friendlies]).pluck(:hero_id)

    @remaining = Build.where.not(hero_id: friendly_hero_ids + params[:enemies] + params[:bans])
    respond_to do |format|
      format.json
    end
  end

  def remaining_heroes
    params[:friendlies] ||= []
    params[:enemies] ||= []
    params[:bans] ||= []

    friendly_hero_ids = Build.where(id: params[:friendlies]).pluck(:hero_id)

    @remaining = Hero.where.not(id: friendly_hero_ids + params[:enemies] + params[:bans])
    respond_to do |format|
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DOTA 2 Pick Wizard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/x-icon' %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-47386813-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

</head>
<body>
  <div class="background-wrapper">
    <header>
      <%= image_tag "dota2-logo.png", class: 'logo' %>
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="399TTVP4SC796">
        <div class="button-wrapper">
          <%= button_tag "Updates", class: "btn donate updates", type: nil %>
          <%= button_tag "About", class: "btn donate about", type: nil %>
          <%= button_tag "Donate", class: "btn donate" %>
        </div>
      </form>
    </header>

    <main>
    <%= yield %>
    </main>

    <div class="modal-about">
      <span class="close close-about">x</span>
      <p>
        This is an app to help you build viable team compositions in Dota 2.
      </p>
      <p>
        Pick heroes for your team, the enemy team, or banned picks, and choose a laning composition,
        and the system will update recommendations on-the-fly!
      </p>
      <p>
        The algorithm will return the 5 best and worst heroes with regards to your team composition,
        as well as heroes that would fit into the enemy composition that you could ban. It also tells you which roles you
        have filled and which ones your team still lacks.
      </p>
      <p>
        The algorithm uses vector math to try and find
        the hero that will best fit into your current lineup to get the team as
        close as possible to an ideal team composition.
      </p>
      <p>
        Each hero is assigned a vector. For each hero that is still selectable, add that hero to the current team and
        calculate the Team Vector by adding the hero vectors together. The distance of that Team Vector from the Ideal Composition Vector
        gives that hero's score, the lower the better. This means that heroes that take the team closer to the Ideal Vector
        receive better scores.
      </p>
      <p>
        The attributes that the algorithm takes into account are: Attack type (melee or ranged),
        the hero's viability in mid, jungle, and off-lanes, and the different roles that each hero is suited to.
      </p>
      <p>
        If you have questions or concerns, or you found a bug, or maybe you just want to thank me, send an email:
        <a href="mailto:evan.hemsley@gmail.com">evan.hemsley@gmail.com</a>
      </p>
      <p>
        Thanks to Benton Anderson and Alex David for helping me with the linear algebra.
      </p>
      <p>
        Special thanks to Robert Douglas and Kevin Goslar for help with the UI design.
      </p>

      <p>
        (c) Evan Hemsley 2013-2014
      </p>
    </div>

    <div class="modal-updates">
      <span class="close close-updates">x</span>
      <br>
      <h3>Changelog</h3>

      <div class="changelog">
        <p>
          4/14/2014
        </p>
        <ul>
          <li>Multiple roles for each hero are now supported.</li>
          <li>System now recommends heroes based on which role will be most effective.</li>
        </ul>

        <p>
          3/25/2014
        </p>
        <ul>
          <li>Added Terrorblade and Phoenix.</li>
        </ul>
      </div>
    </div>

  </div>
</body>
</html>

app/views/picks/hero_picker.haml
.border
  = form_tag pick_assistant_path, method: :post, id: "hero-form", remote: true do |f|
    .appcontainer.cf
      .side-left.col.cf
        .box.your-team
          %h2 Your Team
          .strategy-selector
            %label= select_tag "composition", options_for_select([["Laning...", "balanced"],["2-1-2", "balanced"], ["Jungling", "jungling"], ["Trilane", "trilane"]])
          .search
            = text_field_tag :text, "", class: 'text-input', id: 'friendly-autocomplete', placeholder: "Add a character...", class: "search"
          .characters.cf
            .character.friendly
              .build
              %label.hero_big
              .name
              = hidden_field_tag "friendlies[]", ""
            .character.friendly
              .build
              %label.hero_big
              .name
              = hidden_field_tag "friendlies[]", ""
            .character.friendly
              .build
              %label.hero_big
              .name
              = hidden_field_tag "friendlies[]", ""
            .character.friendly
              .build
              %label.hero_big
              .name
              = hidden_field_tag "friendlies[]", ""
            .character.dead
              %label.hero_big

        .box.recommendations
          %h2 Recommendations
          %h3 Roles
          .roles
            .needed
              .role.needed-role
                Needed
              .role.needed-role
                Needed
            .filled
              .role.filled-role
                Filled
              .role.filled-role
                Filled
          %h3 We Recommend
          .characters.cf.recommend-these
            .character.recommendation
              .build
              %label.hero_big
              .name
            .character.recommendation
              .build
              %label.hero_big
              .name
            .character.recommendation
              .build
              %label.hero_big
              .name
            .character.recommendation
              .build
              %label.hero_big
              .name
            .character.recommendation
              .build
              %label.hero_big
              .name
          %h3 Avoid
          .characters.cf.avoid-these
            .character.avoid
              .build
              %label.hero_big
              .name
            .character.avoid
              .build
              %label.hero_big
              .name
            .character.avoid
              .build
              %label.hero_big
              .name
            .character.avoid
              .build
              %label.hero_big
              .name
            .character.avoid
              .build
              %label.hero_big
              .name
      .side-right.col.cf
        .box.enemy-team
          %h2 Enemy Team
          .search
            = text_field_tag :text, "", class: 'text-input', id: 'enemy-autocomplete', placeholder: "Add enemy hero...", class: "search"
          .characters.cf
            .character.enemy
              %label.hero_big
              .name
              = hidden_field_tag "enemies[]", ""
            .character.enemy
              %label.hero_big
              .name
              = hidden_field_tag "enemies[]", ""
            .character.enemy
              %label.hero_big
              .name
              = hidden_field_tag "enemies[]", ""
            .character.enemy
              %label.hero_big
              .name
              = hidden_field_tag "enemies[]", ""
            .character.enemy
              %label.hero_big
              .name
              = hidden_field_tag "enemies[]", ""

        .box.bans
          %h2 Bans
          .search
            = text_field_tag :text, "", class: 'text-input', id: 'ban-autocomplete', placeholder: "Add banned hero...", class: "search"
          .characters.bans.cf
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""
            .character.banned
              %label.hero_big
              .name
              = hidden_field_tag "bans[]", ""

          %h3 Recommended Bans
          .characters.cf.ban-these
            .character.ban
              %label.hero_big
              .name
            .character.ban
              %label.hero_big
              .name
            .character.ban
              %label.hero_big
              .name
            .character.ban
              %label.hero_big
              .name
            .character.ban
              %label.hero_big
              .name

app/views/shared/_live_search.haml
.search-wrapper
  %fieldset.search
    = fa_icon "search", class: 'search-icon'
    = text_field_tag :text, "", class: 'text-input', id: 'filter', placeholder: 'Search...'
    %span#filter-count